Autenticação de rotas USER.
rudolfoblake/user_microservice pull request #18
Opened 2021-05-20 13:09 UTC by bublitzjr

Realizada a TASK de autenticação de rotas da USER API.
Feito teste do método de autenticação da chave de acesso.

2021-05-20 14:27 UTC, GhostsBR requested changes
Também é necessário dar um pull request no develop.

2021-05-20 14:27 UTC, GhostsBR commented on Tests/TestControllers/test_authController.py
> +    def test_access_key_validation_works(self):
Faltando o teste de quando a exceção é lançada.

2021-05-20 14:27 UTC, GhostsBR commented on app.py
> +    if ac.access_key_validation(dict(request.headers)):
Alterar o `if ac.access_key_validation(dict(request.headers)):` para `if not ac.access_key_validation(dict(request.headers)): return "Invalid access key.", 401`.

2021-05-20 14:27 UTC, GhostsBR commented on app.py
> +    if ac.access_key_validation(dict(request.headers)):
Alterar o `if ac.access_key_validation(dict(request.headers)):` para `if not ac.access_key_validation(dict(request.headers)): return "Invalid access key.", 401`.

2021-05-20 17:32 UTC, LuisNataan commented on Tests/TestControllers/test_authController.py
> +        self.assertTrue(ac.access_key_validation(dict(Key="WADCAlhXPqJ4UL3JwO4fkhsAV8rIyE")))
DONE

2021-05-20 17:32 UTC, LuisNataan commented on app.py
> +    if ac.access_key_validation(dict(request.headers)):
DONE

2021-05-20 17:32 UTC, LuisNataan commented on app.py
> +    if ac.access_key_validation(dict(request.headers)):
DONE

2021-05-20 18:40 UTC, LuisNataan commented on Tests/TestControllers/test_authController.py
> +        self.assertTrue(ac.access_key_validation(dict(Key="WADCAlhXPqJ4UL3JwO4fkhsAV8rIyE")))
DONE

2021-05-20 18:40 UTC, LuisNataan commented on Tests/TestControllers/test_authController.py
> +    def test_access_key_validation_works(self):
DONE

2021-05-21 12:25 UTC, nadiavhansen commented on .vscode/settings.json
> +}
Colocar este arquivo no gitignore.

2021-05-21 12:56 UTC, LuisNataan approved these changes
LGTM

2021-05-21 13:02 UTC, nadiavhansen approved these changes
Show!!

2021-05-21 13:19 UTC, bsadoski approved these changes

2021-05-21 13:20 UTC, merged